[tools]
vp = "latest"
nub = "latest"
sops = "latest"
supabase = "latest"
biome = "latest"
"npm:netlify-cli" = "latest"
dotenv-linter = "latest"
bun = "latest"
glow = "latest"
wrangler = { version = "latest", allow_builds = ["esbuild", "sharp", "workerd"] }
[env]
SOPS_AGE_RECIPIENTS = "age1a9p2k3u40mvdntpad4ga7akvnnqqwm6eskfr2yxkgq3u9lp7jfns2wgqty, age155th0ptdjf3gkp7pmzqcepe9kec9n3w32l87czf29fda4a2gj49ql0pg8a"
_.file = { path = ".env" }
[tasks]
dbsetup = { run = "supabase db push" }
dbgenerate = { run = "supabase db generate" }
build = { run = "vp build" }
lint = { run = "biome lint" }
format = { run = "biome format . --write" }
encrypt = { run = "sops -e -i .env && mv .env .env.example" }
decrypt = { run = "mv .env.example .env && sops -d -i .env " }
