/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as AuthenticatedRouteImport } from "./routes/_authenticated";
import { Route as AuthenticatedCanvasIdRouteImport } from "./routes/_authenticated/canvas/$id";
import { Route as AuthenticatedIndexRouteImport } from "./routes/_authenticated/index";
import { Route as ApiSplatRouteImport } from "./routes/api.$";
import { Route as ApiRpcSplatRouteImport } from "./routes/api.rpc.$";
import { Route as LoginRouteImport } from "./routes/login";

const AuthenticatedRoute = AuthenticatedRouteImport.update({
	id: "/_authenticated",
	getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
	id: "/login",
	path: "/login",
	getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
	id: "/",
	path: "/",
	getParentRoute: () => AuthenticatedRoute,
} as any);
const ApiSplatRoute = ApiSplatRouteImport.update({
	id: "/api/$",
	path: "/api/$",
	getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedCanvasIdRoute = AuthenticatedCanvasIdRouteImport.update({
	id: "/canvas/$id",
	path: "/canvas/$id",
	getParentRoute: () => AuthenticatedRoute,
} as any);
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
	id: "/api/rpc/$",
	path: "/api/rpc/$",
	getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
	"/": typeof AuthenticatedIndexRoute;
	"/login": typeof LoginRoute;
	"/api/$": typeof ApiSplatRoute;
	"/canvas/$id": typeof AuthenticatedCanvasIdRoute;
	"/api/rpc/$": typeof ApiRpcSplatRoute;
}
export interface FileRoutesByTo {
	"/login": typeof LoginRoute;
	"/api/$": typeof ApiSplatRoute;
	"/": typeof AuthenticatedIndexRoute;
	"/canvas/$id": typeof AuthenticatedCanvasIdRoute;
	"/api/rpc/$": typeof ApiRpcSplatRoute;
}
export interface FileRoutesById {
	__root__: typeof rootRouteImport;
	"/_authenticated": typeof AuthenticatedRouteWithChildren;
	"/login": typeof LoginRoute;
	"/api/$": typeof ApiSplatRoute;
	"/_authenticated/": typeof AuthenticatedIndexRoute;
	"/_authenticated/canvas/$id": typeof AuthenticatedCanvasIdRoute;
	"/api/rpc/$": typeof ApiRpcSplatRoute;
}
export interface FileRouteTypes {
	fileRoutesByFullPath: FileRoutesByFullPath;
	fullPaths: "/" | "/login" | "/api/$" | "/canvas/$id" | "/api/rpc/$";
	fileRoutesByTo: FileRoutesByTo;
	to: "/login" | "/api/$" | "/" | "/canvas/$id" | "/api/rpc/$";
	id:
		| "__root__"
		| "/_authenticated"
		| "/login"
		| "/api/$"
		| "/_authenticated/"
		| "/_authenticated/canvas/$id"
		| "/api/rpc/$";
	fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
	AuthenticatedRoute: typeof AuthenticatedRouteWithChildren;
	LoginRoute: typeof LoginRoute;
	ApiSplatRoute: typeof ApiSplatRoute;
	ApiRpcSplatRoute: typeof ApiRpcSplatRoute;
}

declare module "@tanstack/react-router" {
	interface FileRoutesByPath {
		"/_authenticated": {
			id: "/_authenticated";
			path: "";
			fullPath: "/";
			preLoaderRoute: typeof AuthenticatedRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/login": {
			id: "/login";
			path: "/login";
			fullPath: "/login";
			preLoaderRoute: typeof LoginRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/_authenticated/": {
			id: "/_authenticated/";
			path: "/";
			fullPath: "/";
			preLoaderRoute: typeof AuthenticatedIndexRouteImport;
			parentRoute: typeof AuthenticatedRoute;
		};
		"/api/$": {
			id: "/api/$";
			path: "/api/$";
			fullPath: "/api/$";
			preLoaderRoute: typeof ApiSplatRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/_authenticated/canvas/$id": {
			id: "/_authenticated/canvas/$id";
			path: "/canvas/$id";
			fullPath: "/canvas/$id";
			preLoaderRoute: typeof AuthenticatedCanvasIdRouteImport;
			parentRoute: typeof AuthenticatedRoute;
		};
		"/api/rpc/$": {
			id: "/api/rpc/$";
			path: "/api/rpc/$";
			fullPath: "/api/rpc/$";
			preLoaderRoute: typeof ApiRpcSplatRouteImport;
			parentRoute: typeof rootRouteImport;
		};
	}
}

interface AuthenticatedRouteChildren {
	AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute;
	AuthenticatedCanvasIdRoute: typeof AuthenticatedCanvasIdRoute;
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
	AuthenticatedIndexRoute: AuthenticatedIndexRoute,
	AuthenticatedCanvasIdRoute: AuthenticatedCanvasIdRoute,
};

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
	AuthenticatedRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
	AuthenticatedRoute: AuthenticatedRouteWithChildren,
	LoginRoute: LoginRoute,
	ApiSplatRoute: ApiSplatRoute,
	ApiRpcSplatRoute: ApiRpcSplatRoute,
};
export const routeTree = rootRouteImport
	._addFileChildren(rootRouteChildren)
	._addFileTypes<FileRouteTypes>();

import type { createStart } from "@tanstack/react-start";
import type { getRouter } from "./router.tsx";

declare module "@tanstack/react-start" {
	interface Register {
		ssr: true;
		router: Awaited<ReturnType<typeof getRouter>>;
	}
}
